# Generated by Django 5.2.5 on 2025-08-11 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initia;'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name=' body',
            new_name='body',
        ),
    ]
